#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p $DIR/homecache
mkdir -p $DIR/build

DEF_DOCKER="lnx32"
if [ "$1" == "w32" ];
then
    DEF_DOCKER="w32"
fi

DOCKER_NAME="safelists_build_$DEF_DOCKER"

docker rm -f $DOCKER_NAME
docker run --name $DOCKER_NAME \
    -d \
    -e LOCAL_USER_ID=`id -u $USER` -v $HOME/Desktop/ramdisk/stmp:/tmp -v $DIR:/safelists/ -v $DIR/homecache:/root/ \
    -e VIRTUAL_DIR=/home/deividas/Desktop/Dropbox/MyPrj/SafeLists \
    -e VIRTUAL_BUILD_DIR=/home/deividas/Desktop/ramdisk/stmp/build safelists_templatious:v1 sleep 1000000

docker exec -it safelists_build_lnx32 /safelists/innerbuild
