#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p $DIR/homecache

docker run -it -v $DIR:/safelists/ -v $DIR/homecache:/root/ --rm safelists_templatious:v1 /safelists/innerbuild
