#!/bin/bash

export SL=/safelists/

mkdir $SL/build
pushd $SL/build

source /safelists/mxeentry

export CMXE_TOOLCHAIN=-DCMAKE_TOOLCHAIN_FILE=/mxe/usr/i686-pc-linux-gnu.static/share/cmake/mxe-conf.cmake

cmake -DCARGO_COMMAND=/mxe/usr/i686-pc-linux-gnu.static/bin/cargo \
    -DCMAKE_BUILD_TYPE=Debug "$@" -DPLUMBING_LUA_INCLUDE="<lua.hpp>" $CMXE_TOOLCHAIN $SL

make -j 1 VERBOSE=1

