#!/bin/bash

export SL=/safelists/

mkdir $SL/build
pushd $SL/build

CMXE_TOOLCHAIN=-DCMAKE_TOOLCHAIN_FILE=/mxe/usr/i686-pc-linux-gnu.static/share/cmake/mxe-conf.cmake

cmake -DCMAKE_BUILD_TYPE=Debug "$@" -DPLUMBING_LUA_INCLUDE="<lua.hpp>" $CMXE_TOOLCHAIN $SL

make -j 8

