#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker run -it -v $DIR:/safelists/ -v $DIR/homecache:/root/ --rm safelists_templatious:v1 bash -c 'source /safelists/mxeentry && /bin/bash'

