#!/bin/bash

# $1 - file list to package
# $2 - base input directory (no trailing slash)
# $3 - output packaging directory

INPUT_FILE="$1"
BASE_INPUT_DIR="$2"
OUTPUT_DIR="$3"
RAW_DIR="$OUTPUT_DIR/raw"

rm -rf "$OUTPUT_DIR"
mkdir -p "$RAW_DIR"

function getsplit {
    RES=$( echo "$2" | cut -f$1 -d\| )
    echo "$RES"
}

while read -r line || [[ -n "$line" ]]; do
    # skip comments
    if [[ $line != \#* ]];
    then
        FIRST_RULE=$( getsplit 1 "$line" )
        case $FIRST_RULE in
            normal)
                FROM=$( getsplit 2 "$line" )
                TO=$( getsplit 3 "$line" )
                INPATH="$BASE_INPUT_DIR/$FROM"
                OUTPATH="$RAW_DIR/$TO"
                if [ "-" = "$TO" ];
                then
                    OUTPATH="$RAW_DIR/$FROM"
                fi

                TO_CREATE=$( dirname "$OUTPATH" )
                mkdir -p "$TO_CREATE"
                cp -v "$INPATH" "$OUTPATH"
            ;;
            directory)
                FROM=$( getsplit 2 "$line" )
                TO=$( getsplit 3 "$line" )
                INPATH="$BASE_INPUT_DIR/$FROM"
                OUTPATH="$RAW_DIR/$TO"
                if [ "-" = "$TO" ];
                then
                    OUTPATH="$RAW_DIR/$FROM"
                fi

                TO_CREATE=$( dirname "$OUTPATH" )
                mkdir -p "$TO_CREATE"
                cp -rv "$INPATH" "$OUTPATH"
            ;;
        esac
    fi
done < "$INPUT_FILE"
