#!/bin/bash

# $1 - file list to package
# $2 - base input directory (no trailing slash)
# $3 - output packaging directory

INPUT_FILE="$1"
BASE_INPUT_DIR="$2"
OUTPUT_DIR="$3"
RAW_DIR="$OUTPUT_DIR/raw"

mkdir -p "$OUTPUT_DIR"
mkdir -p "$RAW_DIR"

function getsplit {
    RES=$( echo "$2" | cut -f$1 -d\| )
    echo "$RES"
}

while read -r line || [[ -n "$line" ]]; do
    # skip comments
    if [[ $line != \#* ]];
    then
        FIRST_RULE=$( getsplit 1 "$line" )
        case $FIRST_RULE in
            normal)
                FROM=$( getsplit 2 "$line" )
                TO=$( getsplit 3 "$line" )
                if [ "-" = "$TO" ];
                then
                    cp -v "$BASE_INPUT_DIR/$FROM" "$RAW_DIR/$FROM"
                else
                    cp -v "$BASE_INPUT_DIR/$FROM" "$RAW_DIR/$TO"
                fi
            ;;
            directory)
                FROM=$( getsplit 2 "$line" )
                TO=$( getsplit 3 "$line" )
                if [ "-" = "$TO" ];
                then
                    cp -rv "$BASE_INPUT_DIR/$FROM" "$RAW_DIR/$FROM"
                else
                    cp -rv "$BASE_INPUT_DIR/$FROM" "$RAW_DIR/$TO"
                fi
            ;;
        esac
    fi
done < "$INPUT_FILE"
