#!/bin/bash

# $1 - zip to sign
# $2 - private key to use
# $3 - signjson executable file
# $4 - dir to cd to
# $5 - signature.json
# $6 - tmp work dir
# $7 - resulting zip output

TO_SIGN="$1"
PRIVATE_KEY="$2"
SIGN_JSON="$3"
SIGN_WORK_DIR="$4"
JSON_TO_SIGN="$5"
WORK_DIR="$6"
OUTPUT_ZIP="$7"

# copy paste from
# stackoverflow.com/questions/2564634/convert-absolute-path-into-relative-path-given-a-current-directory-using-bash
function relfromabs {
    # both $1 and $2 are absolute paths beginning with /
    # returns relative path to $2/$target from $1/$source
    source=$1
    target=$2

    common_part=$source # for now
    result="" # for now

    while [[ "${target#$common_part}" == "${target}" ]]; do
        # no match, means that candidate common part is not correct
        # go up one level (reduce common part)
        common_part="$(dirname $common_part)"
        # and record that we went back, with correct / handling
        if [[ -z $result ]]; then
            result=".."
        else
            result="../$result"
        fi
    done

    if [[ $common_part == "/" ]]; then
        # special case for root (no common path)
        result="$result/"
    fi

    # since we now have identified the common part,
    # compute the non-common part
    forward_part="${target#$common_part}"

    # and now stick all parts together
    if [[ -n $result ]] && [[ -n $forward_part ]]; then
        result="$result$forward_part"
    elif [[ -n $forward_part ]]; then
        # extra slash removal
        result="${forward_part:1}"
    fi

    echo $result
}

#RANDOM_DIR="$WORK_DIR/$( date | md5sum | cut -f1 -d\  )"
RANDOM_DIR="$WORK_DIR"
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"

unzip "$TO_SIGN" -d "$RANDOM_DIR"
pushd "$RANDOM_DIR/$SIGN_WORK_DIR"
$SIGN_JSON "$PRIVATE_KEY" "$JSON_TO_SIGN"
popd

cp -v "$TO_SIGN" "$RANDOM_DIR/"
BASENAME=$( basename $TO_SIGN )
pushd "$RANDOM_DIR"
TO_ADD=$( relfromabs "$RANDOM_DIR" "$RANDOM_DIR/$SIGN_WORK_DIR/$JSON_TO_SIGN" | sed -E "s/\/\.\//\//" )
zip -ru -9 "$RANDOM_DIR/$BASENAME" "$TO_ADD"
mv "$RANDOM_DIR/$BASENAME" "$OUTPUT_ZIP"
